# Generated by Django 5.2.6 on 2025-09-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('slippers', 'Slippers'), ('boots', 'Boots')], default='shoes', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoe/'),
        ),
    ]
