# Generated by Django 5.2.6 on 2025-09-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shoes_category_alter_shoes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
